#

version: '3'
services:
  v2board:
    container_name: ${CONTAINER_NAME}
    image: "${REPOSITORY}/${IMAGE_NAME}:${IMAGE_TAG}"
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      # v2board 配置
      - APP_NAME=${APP_NAME}
      - APP_KEY=${APP_KEY}
      - BASEURL=${PROTOCOL}://${DOMAIN}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      # 构建配置
      - DBMODE=${DBMODE}
      - REINSTALL=${REINSTALL}
      - REPOVISI=${REPOVISI}
      - GITREPO=${GITREPO}
      - REPOURL=${REPOURL}
      - BRANCH=${BRANCH}
      # redis 配置
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      # admin 配置
      - ADMIN_MAIL=${ADMIN_MAIL}
      # 主题选择
      - THEME_MODEL={THEME_MODEL}
      - THEME_TAG={THEME_TAG}
    depends_on:
      - mariadb
      - nginx
      - redis-sspanel
    volumes:
      - ${NGINX_WWW_PATH}/${APP_HOME}:/app
      - v2board_config:/opt/bitnami/backup
    restart: always
    networks:
      - ext_network

  nginx:
    container_name: nginx
    image: docker.io/nginx:alpine
    restart: always
    ports:
     - "80:80"
     - "443:443"
    volumes:
     - ${NGINX_WWW_PATH}:/usr/share/nginx/html
     - ${NGINX_CONF_PATH}:/etc/nginx/conf.d
     - ${NGINX_LOG_PATH}:/var/log/nginx
     - ${NGINX_SSL_PATH}:/etc/nginx/ssl
    networks:
      - ext_network

  mariadb:
    container_name: mariadb
    image: docker.io/bitnami/mariadb:10.9
    # 需要外网访问，请取消注释
    ports:
      - '${DB_PORT}:3306'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      # - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MARIADB_USER=${DB_USERNAME}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=${DB_DATABASE}
      - MARIADB_CHARACTER_SET=${DB_CHARACTER_SET}
      - MARIADB_COLLATE=${DB_COLLATE}
    volumes:
      - mariadb_data:/bitnami/mariadb
    restart: unless-stopped
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
    networks:
      - ext_network

  redis_v2board:
    container_name: redis_v2board
    image: docker.io/bitnami/redis:7.0.12
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      # - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    # ports:
    # - '${REDIS_PORT}:6379'
    volumes:
      - redis_v2board_data:/bitnami/redis/data
    restart: unless-stopped
    networks:
      - ext_network

volumes:
  mariadb_data:
    driver: local
  redis_v2board_data:
    driver: local
  v2board_config:
    driver: local

networks:
  ext_network:
    driver: bridge
    ipam:
      config:
        - subnet: "172.16.238.0/24"
          gateway: "172.16.238.1"


